### ISSUE TITLE
Tile type

### ISSUE THREAD

**Issue by flxbe** [flxbe/villages#8]
* Only send the `TILE_TYPE` for each map tile. Infer the properties of the tile from its type, like `buildable`.
* Introduce new property to differentiate between being able to build a building and being able to build a street.

**Comment by kruesemann** [comment]
Will we handle streets as a tile type or as buildings?

**Comment by flxbe** [comment]
Both, streets should have their own tile type as well as the properties of a building (like beeing buildable and removable by the user). Tiles underneath other buildings should however still be represented with the type `TILE_BUILDING`. The different tile types are only to allow units to go over streets, while avoiding paths through other buildings.
